otp:
  dht:
    interval: 360
    key: YlyOjZoSJ2e1nOTEQow6hvJHhdOymg4wdrDkOKoQRId
    length: 43
  crypto:
    interval: 360
    key: jyzqLdahCwZZ05GEdGw7ZrOZs0oA19tlOinY4uu7tQd
    length: 43
room: NUDZolnz4pn1RQIMHcHGFbJ8GkEte9QSDJrneFmRw5u
rendezvous: g3vcQQQpbqe2ivyyDTi59eZv8ELxYZahWWuLUB2R1bk
mdns: XsCQnq4jZuYYWEElZIPnlWAhDC4a30m95y3NmYzhW5p
max_message_size: 20971520

