otp:
  dht:
    interval: 360
    key: HY2Pvju1tL7dMiMOuMrvV9PFZJdqc8fl4BsJa82Jrd6
    length: 43
  crypto:
    interval: 360
    key: z2g53A6CGKHQQOHgm08f1aZDYmGKSQFYCjP7aqMtT7k
    length: 43
room: wH3JdttE00BJpQjJmzo4ego4Nhc5isghvJssiEBCY0l
rendezvous: 9PDGNoiHLAELUzIL8rzZrfpk70tZtIAQvCE7flObPux
mdns: mlCX79EIDHeoKcZXqpy8vxGkvt2ultdkQWAEuFPOU3B
max_message_size: 20971520

