otp:
  dht:
    interval: 360
    key: kpzweDR3j5vIv0E3JYOhYWDqQE4U01IM3JhYQ0ZD0Wt
    length: 43
  crypto:
    interval: 360
    key: gPEb2NSXdNGndIopvVrRviF1DVPC72MInO6SgNpWsWP
    length: 43
room: Ffa3P84ZPbPJXJrSZ5gn0emhWgBmjkX6TVV7NSJi6ty
rendezvous: foUN1H6xHbXyiYs2kvATyULV8C2iE87xweOhe27jr7s
mdns: BQNTXs7u9AoOcRYfsM79EaSHeQXso0I0XM3FT5283vh
max_message_size: 20971520

